# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

nav-menu:
  - label: Nos Réalisations
    link: /
    class: navMenu-item-default
    
  - label: Nos Savoir-faire
    link: /page/nos-savoir-faire
    class: navMenu-item-default
    
  - label: A propos
    link: /page/a-propos
    class: navMenu-item-default
    submenu:
        - label: Qualifications
          link: '/page/a-propos#qualifications'
        - label: Nos outils
          link: '/page/a-propos#outils'
        - label: Notre équipe
          link: '/page/a-propos#equipe'
        - label: Nos implantations
          link: '/page/a-propos#implantations'
    
  - label: Contactez-nous
    link: /page/contactez-nous
    class: navMenu-item-default
    submenu:
        - label: Formulaire de contact
          link: '/page/contactez-nous#contact'
        - label: Nos implantations
          link: '/page/contactez-nous#implantations'
    
  - label: Espace Client
    link: https://www.colorjazz.info/partitions.php
    target: _blank
    class: navMenu-item-client
    

footer-menu:
    - label: Nos Réalisations
      link: /

    - label: Nos Savoir-faire
      link: /page/nos-savoir-faire

    - label: A propos
      link: /page/a-propos

    - label: Contactez-nous
      link: /page/contactez-nous


# ne sert pas, que pour exemple 

main:
  - label: Home
    title: This is the <b>first<b> menu item.
    link: homepage
    class: homepage
  - label: About
    link: page/2
    submenu:
        - label: Sub 1
          link: entry/39
        - label: Sub 2
          class: menu-item-class
          link: entry/40
        - link: entry/41 # These two have no `label`, so they will show up as the title
        - class: sub-class
          link: page/42
  - label: All pages
    link: pages/
  - label: The Bolt site
    link: https://boltcms.io
    class: bolt-site
    title: Visit the excellent Bolt website!

foo: bar
